### ISSUE TITLE
Error when installing the package version 3.7.95

### ISSUE THREAD

**Issue by lucalves** [ripsware/community_material_icon#9]
Hello, when I add the version (3.7.95) that is in the README:

```yaml
community_material_icon: ^3.7.95
```

And after that I execute the command flutter pub get, an error is returned informing that the version resolution failed.

<img src="https://i.imgur.com/1E3D83u.png">

**Comment by mono0926** [comment]
@lucalves 

`^3.5.95` is latest for now, `3.7.95` doesn't exist even though [README suggests it](https://github.com/ripsware/community_material_icon#installation).
https://pub.dev/packages/community_material_icon/versions

**Comment by lucalves** [comment]
@mono0926 

I believe #11 will solve that. Thanks.
